### ISSUE TITLE
Jeet and rupture support

### ISSUE THREAD

**Issue by jamelt** [hexojs/hexo-renderer-stylus#12]
Can this be configured to support Jeet and Rupture without having to hack the renderer.js file?

**Comment by tomap** [comment]
Just to be sure, do you mean http://jeet.gs/ and https://github.com/jescalan/rupture or else?

**Comment by jamelt** [comment]
Yes, precisely. :sweat_smile:

**Comment by jamelt** [comment]
Hey I'll implement this for you and submit a pull request.
