### ISSUE TITLE
Publish the latest version to NPM registry?

### ISSUE THREAD

**Issue by iissnan** [hexojs/hexo-renderer-stylus#17]
Could you please publish the latest version (0.3.2) to the NPM registry?
And is it possible to publish the newest version to NPM registry when a new version is bumped?

Thanks.

**Comment by NoahDragon** [comment]
poke @tommy351

**Comment by NoahDragon** [comment]
Updated to 0.3.3: https://www.npmjs.com/package/hexo-renderer-stylus
