### ISSUE TITLE
won't detect changes to imported files

### ISSUE THREAD

**Issue by TBlank72** [hexojs/hexo-renderer-stylus#9]
When I use "hexo generate", changes to files that are @import into the main .styl file aren't detected.  If I edit the main .styl file and "hexo generate", then change it back and "hexo generate" again, I can get it to work, but it just seems like extra work.  Is there a setting that I'm missing that tells it to watch for changes to all files?

Thanks, and sorry for the noob question.

**Comment by BrunoCartier** [comment]
Same problem here.
When a file has only imports, it won't be generated :/

**Comment by shinux** [comment]
same here

**Comment by mamboer** [comment]
same issue here

**Comment by GazEdge** [comment]
same issue here v0.3.3 . Seems like imported files are not considered when looking at what files have been updated.
